-- =============================================================================
-- seed.sql
-- Sample data for local development and testing.
-- Safe to re-run: existing rows are skipped via ON CONFLICT DO NOTHING.
-- Run AFTER V10__migrate.sql (or V1–V9) has been applied.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Interests
-- ---------------------------------------------------------------------------

INSERT INTO interests (interest_name) VALUES
    ('Engineering'),
    ('Music'),
    ('Gaming'),
    ('Basketball'),
    ('Soccer'),
    ('Film'),
    ('Cooking'),
    ('Photography'),
    ('Hiking'),
    ('Finance')
ON CONFLICT (interest_name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- PNMs
-- ---------------------------------------------------------------------------
-- IDs are generated by the DB; we reference them below by sub-select on email
-- (which is a natural unique key for seed purposes).

INSERT INTO pnms (first_name, last_name, class_year, status_type, email, phone_number) VALUES
    ('James',   'Carter',   'FRESHMAN',    'DELTA', 'james.carter@uni.edu',   '555-101-0001'),
    ('Maria',   'Lopez',    'SOPHOMORE',   'SIGMA', 'maria.lopez@uni.edu',    '555-101-0002'),
    ('Tyler',   'Brooks',   'JUNIOR',      'PHI',   'tyler.brooks@uni.edu',   '555-101-0003'),
    ('Aisha',   'Patel',    'SENIOR',      'DELTA', 'aisha.patel@uni.edu',    '555-101-0004'),
    ('Connor',  'Wu',       'SUPER_SENIOR','SIGMA', 'connor.wu@uni.edu',      '555-101-0005'),
    ('Sophia',  'Nguyen',   'FRESHMAN',    NULL,    'sophia.nguyen@uni.edu',  '555-101-0006'),
    ('Marcus',  'Johnson',  'SOPHOMORE',   'PHI',   'marcus.johnson@uni.edu', '555-101-0007'),
    ('Elena',   'Rivera',   'JUNIOR',      'DELTA', 'elena.rivera@uni.edu',   '555-101-0008'),
    ('Noah',    'Kim',      'SENIOR',      NULL,    'noah.kim@uni.edu',       '555-101-0009'),
    ('Priya',   'Sharma',   'FRESHMAN',    'SIGMA', 'priya.sharma@uni.edu',   '555-101-0010')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- On-campus housing  (PNMs 1, 2, 3, 6, 7, 10)
-- ---------------------------------------------------------------------------

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'SPEED',        '101' FROM pnms WHERE email = 'james.carter@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'BSB',          '204' FROM pnms WHERE email = 'maria.lopez@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'BLUMBERG',     '312' FROM pnms WHERE email = 'tyler.brooks@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'LAKESIDE',     '405' FROM pnms WHERE email = 'sophia.nguyen@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'MEES',         '118' FROM pnms WHERE email = 'marcus.johnson@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO on_campus_housing (pnm_id, dorm, room_number)
SELECT id, 'APARTMENTS EAST', '2B' FROM pnms WHERE email = 'priya.sharma@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Off-campus housing  (PNMs 4, 5, 8, 9)
-- ---------------------------------------------------------------------------

INSERT INTO off_campus_housing (pnm_id, street_address, city, state, zip_code)
SELECT id, '742 Evergreen Terrace', 'Springfield', 'IL', '62701'
FROM pnms WHERE email = 'aisha.patel@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO off_campus_housing (pnm_id, street_address, city, state, zip_code)
SELECT id, '1600 Maple Ave Apt 3', 'Shelbyville', 'IL', '62565'
FROM pnms WHERE email = 'connor.wu@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO off_campus_housing (pnm_id, street_address, city, state, zip_code)
SELECT id, '221 Baker Street', 'Capital City', 'IL', '62701'
FROM pnms WHERE email = 'elena.rivera@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

INSERT INTO off_campus_housing (pnm_id, street_address, city, state, zip_code)
SELECT id, '55 Water Street Apt 9C', 'Springfield', 'IL', '62704'
FROM pnms WHERE email = 'noah.kim@uni.edu'
ON CONFLICT (pnm_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- PNM interests
-- ---------------------------------------------------------------------------

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'james.carter@uni.edu'   AND i.interest_name IN ('Engineering', 'Gaming')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'maria.lopez@uni.edu'    AND i.interest_name IN ('Music', 'Photography')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'tyler.brooks@uni.edu'   AND i.interest_name IN ('Basketball', 'Film')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'aisha.patel@uni.edu'    AND i.interest_name IN ('Finance', 'Cooking')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'connor.wu@uni.edu'      AND i.interest_name IN ('Soccer', 'Gaming', 'Film')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'sophia.nguyen@uni.edu'  AND i.interest_name IN ('Hiking', 'Photography')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'marcus.johnson@uni.edu' AND i.interest_name IN ('Basketball', 'Engineering')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'elena.rivera@uni.edu'   AND i.interest_name IN ('Music', 'Cooking', 'Hiking')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'noah.kim@uni.edu'       AND i.interest_name IN ('Finance', 'Soccer')
ON CONFLICT DO NOTHING;

INSERT INTO pnm_interests (pnm_id, interest_id)
SELECT p.id, i.id FROM pnms p, interests i
WHERE p.email = 'priya.sharma@uni.edu'   AND i.interest_name IN ('Engineering', 'Film', 'Gaming')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Users & Roles
-- Sample password hashes use bcrypt with 10 rounds for 'password123'
-- ---------------------------------------------------------------------------

INSERT INTO users (username, email, password_hash) VALUES
    ('admin_user', 'admin@example.com', '$2b$10$w0s2hBqV8k4eR5gO7/0eG.b1F5kKkV5V8F7U5XkYnE3mP2lQq1.ae'),
    ('dic_user',   'dic@example.com',   '$2b$10$w0s2hBqV8k4eR5gO7/0eG.b1F5kKkV5V8F7U5XkYnE3mP2lQq1.ae'),
    ('std_user',   'user@example.com',  '$2b$10$w0s2hBqV8k4eR5gO7/0eG.b1F5kKkV5V8F7U5XkYnE3mP2lQq1.ae')
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_name)
SELECT user_id, 'ADMIN'::role FROM users WHERE username = 'admin_user'
ON CONFLICT (user_id, role_name) DO NOTHING;

INSERT INTO user_roles (user_id, role_name)
SELECT user_id, 'DIC'::role FROM users WHERE username = 'dic_user'
ON CONFLICT (user_id, role_name) DO NOTHING;

INSERT INTO user_roles (user_id, role_name)
SELECT user_id, 'USER'::role FROM users WHERE username = 'std_user'
ON CONFLICT (user_id, role_name) DO NOTHING;
